SET DOTNET_EnableDiagnostics=1
SET COR_ENABLE_PROFILING=1
SET CORECLR_ENABLE_PROFILING=1
SET COMPlus_PerfMapEnabled=1
SET COR_PROFILER={10B46309-C972-4F33-B5AB-5E6E3EBA2B1A}
SET CORECLR_PROFILER={10B46309-C972-4F33-B5AB-5E6E3EBA2B1A}
SET COR_PROFILER_PATH=.\x64\Release\OctoProfiler.dll
SET CORECLR_PROFILER_PATH_64=.\x64\Release\OctoProfiler.dll
SET OCTO_PROFILER_FILE=log.txt
SET OCTO_LOGGER_INCLUDE_TS=true
SET TEST_PROGRAM=..\test\HelloProfiler\bin\Debug\net8.0\HelloProfiler.exe
IF "%1" == "ENTERLEAVE" (
    SET OCTO_MONITOR_ENTERLEAVE=true
)
IF "%1" == "DEBUGNEW" (
    "WinDbgX" %TEST_PROGRAM%
    GOTO :END
)
IF "%1" == "DEBUG" (
    "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe" %TEST_PROGRAM%
    GOTO :END
) ELSE (
    START /WAIT /B %TEST_PROGRAM%
)

:END
SET COR_ENABLE_PROFILING=
SET CORECLR_ENABLE_PROFILING=
SET COMPlus_PerfMapEnabled=
SET CORECLR_PROFILER_PATH_64=
SET CORECLR_PROFILER=
SET COR_PROFILER_PATH=
SET COR_PROFILER=
